### ISSUE TITLE
.env sample에는 텔레그램이 존재하는데 환경변수에는 주입되고 있지 않습니다.

### ISSUE THREAD

**Issue by 132262B** [techinpark/auto-lottery#4]
.env sample에는 텔레그램 web hook 이 존재하는데 환경변수에서는 주입하지 않는것 같은데 사용되지 않고 있는건가요?

**Comment by techinpark** [comment]
@132262B 네 텔레그램으로 전송하는 로직은 별도로 존재하지 않습니다 해당 봇의 기반이되는 오픈소스에서 사용하던 코드를 재활용해서 같이 들어갔던것 같습니다!

**Comment by 132262B** [comment]
확인 감사합니다 ㅎㅎ
